[package]
name = "lumina-typesystem"
version = "0.2.0"
edition = "2024"
author = "simvux"

[dependencies]
derive-new = "0.7.0"
itertools = "0.14.0"
lumina-key = { path = "../lumina-key" }
serde = { version = "1.0.228", features = ["serde_derive"] }
tracing = "0.1.44"

[dev-dependencies]
tracing-subscriber = { version = "0.3.19", features = ["env-filter"] }
tracing-tree = "0.4.0"
