[workspace]
members = [
    "lumina",
    "lumina-parser",
    "lumina-util",
    "lumina-key",
    "lumina-compiler",
    "lumina-typesystem",
    "lumina-treesitter",
    # "lumina-typesystem-repl",
    # "lumina-collections",
    "lumina-tokentree"
, "lumina-patterns"]
exclude = [
  # Compiled separately with different flags as a staticlib
  "lumina-gc"
]
resolver = "2"
