[package]
name = "lumina-parser"
version = "0.1.0"
authors = ["Simon <simon.larsson-general@protonmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lumina-util = { path = "../lumina-util/" }
lumina-key = { path = "../lumina-key" }
lumina-tokentree = { path = "../lumina-tokentree" }
itertools = "0.14.0" 
logos = { git = "https://github.com/simvux/logos" }
insta = "1.43.2"
smallvec = "1.15.1"
tracing = "0.1.41"
