#!/bin/env bash

# cargo build -Z build-std=std,panic_abort -Z build-std-features=panic_immediate_abort --target x86_64-unknown-linux-musl
# cargo build --release -Z build-std=std,panic_abort -Z build-std-features=panic_immediate_abort --target x86_64-unknown-linux-musl
# 
# cargo build -Z build-std=std,panic_abort -Z build-std-features=panic_immediate_abort --target x86_64-unknown-linux-gnu
# cargo build --release -Z build-std=std,panic_abort -Z build-std-features=panic_immediate_abort --target x86_64-unknown-linux-gnu

# cargo build -Z build-std=std --target x86_64-unknown-linux-musl
# cargo build -Z build-std=std --release --target x86_64-unknown-linux-musl

cargo build -Z build-std=std --target x86_64-unknown-linux-gnu
# cargo build -Z build-std=std --release --target x86_64-unknown-linux-gnu
